### ISSUE TITLE
Something went wrong: TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by nwaltham** [CyberAgent/adbkit#24]
It seems that in file:
.\adbkit\lib\adb\command\host-transport\framebuffer.js

line 40 currently reads:
                    stream = _this._convert(meta);
and it should read:
                    stream = _this._convert(meta,format);

**Comment by sorccu** [comment]
Sorry, took a sweet long time. This should be fixed in 2.2.0.
