### ISSUE TITLE
Attempting to pull a non-existent file causing the client to hang.

### ISSUE THREAD

**Issue by muffinresearch** [CyberAgent/adbkit#29]
Using the example in the docs [1]  and pointing it at a non-existent file the client hangs. I'd expect that it would handle the case of the file on the device not existing and error.

[1] https://github.com/CyberAgent/adbkit#pulling-a-file-from-all-connected-devices

**Comment by sorccu** [comment]
Thanks for reporting it, I'm a bit busy right now, but will confirm & take a look a bit later.

**Comment by sorccu** [comment]
Should be fixed 2.2.0. You'll get an 'error' event on the transfer.
