### ISSUE TITLE
Support destination directory for client.pull

### ISSUE THREAD

**Issue by op1ekun** [CyberAgent/adbkit#31]
The `adb pull` command supports both `source` and `destination` so use can pull files to the desired directory like this: ` adb pull sdcard/AndroidAutomation/TestResults/ C:/tmp`

Looking into client.js: `Client.prototype.pull = function(serial, path, callback)`
I can see it supports only source path.

**Comment by sorccu** [comment]
Hi,

`client.pull()` returns with a stream that you can store anywhere you want. You can choose the target path with, for example, `fs.createWriteStream()`. See https://github.com/CyberAgent/adbkit#pulling-a-file-from-all-connected-devices for one example.

**Comment by op1ekun** [comment]
Does it mean I can't just pull all the files form a directory located on a device?
From the example it look like I can only pull them one by one, and I need to know their names.

I just need to  grab all the files and move them to the temp directory from where they are indexed by Splunk.

**Comment by sorccu** [comment]
You would need to first list the directory contents with `client.readdir()` ([example](https://github.com/CyberAgent/adbkit#list-files-in-a-folder)) and then pull each file separately (and decide how to handle directories). You could also try using `client.syncService()` for less overhead if you have many files, but it's a bit more involved.

**Comment by op1ekun** [comment]
I'll just stick to plain `adb pull` for this specific use case. Thanks!

**Comment by BraunreutherA** [comment]
Hi, 

if somebody needs this functionality - this is a basic implementation for recursive fetching of files with an destination folder. 

```javascript
import fs from 'fs';
import path from 'path';
import Promise from 'bluebird';
import mkdirpCallback from 'mkdirp';
const mkdirp = Promise.promisify(mkdirpCallback);
import path from 'path';

function pullFolder(device, origin, destination) {
  const client = adbkit.createClient();

  return client.readdir(device.id, origin)
    .then((files) => {
      Promise.map(files, (file) => {
        if (file.isFile()) {
          return client.pull(device.id, path.join(origin, file.name))
            .then(transfer => (
              new Promise((resolve, reject) => {
                transfer.on('end', resolve);
                transfer.on('error', reject);
                transfer.pipe(fs.createWriteStream(path.join(destination, file.name)));
              })));
        }
        return mkdirp(path.join(destination, file.name))
          .then(() => pullFolder(device, path.join(origin, file.name),
            path.join(destination, file.name)));
      });
    });
}
```
